import { GoogleGenAI, Type } from "@google/genai";

const apiKey = process.env.GEMINI_API_KEY;

export interface AnalysisResult {
  aiProbability: number;
  reasoning: string;
  confidenceScore: number;
  indicators: {
    label: string;
    value: string;
    description: string;
  }[];
  verdict: 'Human' | 'Likely AI' | 'Highly Likely AI' | 'Mixed';
}

export async function analyzeText(text: string): Promise<AnalysisResult> {
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  const prompt = `
    Analyze the following text to determine if it was generated by an AI or written by a human.
    Look for patterns typical of AI models:
    - High perplexity and burstiness (human-like) vs low (AI-like).
    - Repetitive sentence structures.
    - Lack of personal anecdotes or emotional depth.
    - Overly formal or "perfect" grammar.
    - Common AI transition phrases.

    Text to analyze:
    """
    ${text.slice(0, 5000)} 
    """

    Provide a detailed analysis in JSON format.
  `;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          aiProbability: { type: Type.NUMBER, description: "Probability from 0 to 100 that the text is AI-generated" },
          reasoning: { type: Type.STRING, description: "Detailed explanation of the analysis" },
          confidenceScore: { type: Type.NUMBER, description: "Confidence in this analysis from 0 to 1" },
          verdict: { type: Type.STRING, enum: ["Human", "Likely AI", "Highly Likely AI", "Mixed"] },
          indicators: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                label: { type: Type.STRING },
                value: { type: Type.STRING },
                description: { type: Type.STRING }
              },
              required: ["label", "value", "description"]
            }
          }
        },
        required: ["aiProbability", "reasoning", "confidenceScore", "verdict", "indicators"]
      }
    }
  });

  try {
    const result = JSON.parse(response.text || "{}");
    return result as AnalysisResult;
  } catch (e) {
    console.error("Failed to parse AI response:", e);
    throw new Error("Failed to analyze text. Please try again.");
  }
}
